apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus   # Selector to match pods with the label "app: prometheus"
  ports:
    - protocol: TCP
      port: 9090       # Port on the Service
      targetPort: 9090 # Port on the Pod
